[package]
name = "agbridge-service"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
agbridge-config = { path = "../agbridge-config" }
anyhow.workspace = true
tracing.workspace = true

[target.'cfg(windows)'.dependencies]
windows-service = "0.7"
